api_platform:
    title: Hello API Platform
    version: 1.0.0
    eager_loading:
        enabled: false

    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        multipart: ['multipart/form-data']

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true

    resource_class_directories:
        - '%kernel.project_dir%/src/Controller'
        - '%kernel.project_dir%/src/Dto'
