name: Jobs

on:
  push:
    branches:
      - jobs-branch
  pull_request:
    branches:
      - jobs-branch
  workflow_dispatch:

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        uses: docker/bake-action@v4
        with:
          workdir: backend
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{ github.ref }}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{ github.ref }},mode=max
      - name: Start services
        working-directory: backend
        run: docker compose up -d --wait --no-build
      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          while ! curl -s http://localhost:80 > /dev/null; do
            echo "Waiting for the service to start..."
            sleep 5
          done
